language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo pip install cpp-coveralls

script:
  - ./configure --enable-gcov && make && make tests

after_success:
  - coveralls --root .. -E ".*thirdparty.*" -E ".*dev.*" -E ".*test/.*" --gcov-options '\-lp'
