language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls

script:
  - ./configure && make && make tests

after_success:
  - lcoveralls --retry-count 5
