language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo pip install cpp-coveralls

script:
  - ./configure --enable-gcov && make && make tests

after_success:
  - coveralls -r .. --verbose --gcov-options '\-lp' -E ".*thirdparty.*" -E ".*dev.*" -E ".*test/.*" 
