language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls

script:
  - ./configure && make && make tests && make coverage

after_success:
  - lcoveralls -r ./ --retry-count 5
