language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo pip install cpp-coveralls
  - export GCOV_FLAGS='--coverage'

script:
  - ./configure --enable-gcov && make && make tests

after_success:
  - coveralls -r .. --verbose --gcov-options '\-lp' -x inl -E ".*thirdparty.*" -E ".*dev.*" -E ".*test/.*"
